export type Course = {
  track: string,
  category: string,
  title: string,
  slug: any,
  code: string,
  time: string,
  term: string,
  start: string,
  instructor: string,
  bio: string,
  preview: any,
  tags: { description: string, title: string },
  details: any,
}